all:
  hosts:
    master:
      ansible_host: 89.169.140.116
      ip: 10.10.1.27
      access_ip: 10.10.1.27
    worker-1:
      ansible_host: 158.160.7.226
      ip: 10.10.2.3
      access_ip: 10.10.2.3
    worker-2:
      ansible_host: 158.160.215.46
      ip: 10.10.3.24
      access_ip: 10.10.3.24
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
